### ISSUE TITLE
[Quality interna] Checklist

### ISSUE THREAD

**Issue by Paulabatista** [TiendaNube/Quality#22]
Clareza e Resposta completa
- [ ] Todas as dúvidas do cliente foram respondidas?
- [ ] A informação respondida está correta?
- [ ] A informação respondida está completa? Ou seja, a resposta tem todas as informações necessárias para que as dúvidas do cliente sejam respondidas na primeira interação?
- [ ] Além de responder a pergunta do cliente, informamos os passos de como ele pode conseguir o que precisa?
- [ ] Todas as informações que enviamos são úteis?
- [ ] A redação, ortografia e estrutura do texto permite uma interpretação correta do e-mail pelo cliente?

Personalização e Empatia                                        

- [ ] Falamos conforme a linguagem do merchant?
- [ ] Analisamos a loja do merchant e stats da mesma antes de responder? (nem sempre se aplica)
- [ ] Comentamos sobre a avaliação com o intuito do merchant avaliar nosso atendimento?
- [ ] Não utilizamos linguagem tecnica?

Processo

- [ ] A conversa está com as labels?
- [ ] As labels estão corretas?
- [ ] Olhamos o histórico para saber se existe uma conversa em aberto ou respondida a pouco sobre o mesmo assunto?
- [ ] Todas as informações relevantes para que outro guru responda a conversa estão documentadas no caso?
