### ISSUE TITLE
[Guideline - Estilo de comunicação] Checklist

### ISSUE THREAD

**Issue by Paulabatista** [TiendaNube/Quality#23]
**### Formato do texto**
- [ ] Nossa saudação + despedida foi curta?
- [ ] Deixamos em aberto a possibilidade do cliente trazer mais dúvidas?
- [ ] Nossa resposta estava estruturada e objetiva?          
- [ ] Respondemos em tópicos?     
- [ ] Não utilizamos frases muito longas?         
- [ ] Não utilizamos linguagem técnica?                
- [ ] Não repetimos palavras ao longo do texto?                
- [ ] Não usamos tempo verbal formal?                
- [ ] Não acusamos o merchant?                
- [ ] Recomendamos algo de forma pessoal?                
- [ ] Falamos conforme a linguagem do merchant?                
- [ ] Não usamos quantidade excessiva de emoji?

**### Conteúdo**
- [ ] Usamos vídeos para mostrar passo a passo de determinada configuração?                   
- [ ] Usamos imagens em GIF?                   
- [ ] Encaminhamos o link direto do Admin?                   
- [ ] Enviamos tutoriais para auxiliar com o tema?                  
- [ ] Não enviamos uma sequência muito extensa de links?

**### Empatia**
- [ ] Analisamos a loja/admin do merchant?                   
- [ ] Não incluímos exemplos de configuração/funcionalidade de outra loja?                    
- [ ] Educamos o cliente para que ele busque as informações?                    
- [ ] Fizemos as alterações one-timer para o merchant?                    
- [ ] Demos uma resposta errada e pedimos desculpa?

**### Qualificações**
- [ ] Não pedimos avaliação do merchant?
- [ ] Não incluímos o emoji que o cliente avaliou?

**### Issues**
- [ ] Demos continuidade como se fossemos uma pessoa só?
- [ ] Passamos tranquilidade e empatia?                    
- [ ] Lidamos com o problema de forma positiva?                    
- [ ] Setamos as expectativas do cliente?                    
- [ ] Mostramos que não conseguimos reproduzir o erro?                    
- [ ] Demos contexto do caso?                    
- [ ] Passamos uma solução paliativa?                    
- [ ] Demos update ao cliente?

**### FRs**
- [ ] Não enviamos uma explicação extensa?
- [ ] Enviamos a página de Novidades Nuvem?                    
- [ ] Entendemos o motivo do merchant querer a funcionalidade?                    
- [ ] Demos uma medida paliativa?      

**### Plataformas externas**
- [ ] Auxiliamos o cliente com algo que poderíamos ter feito?

**### FTP**
- [ ] Fomos empáticos ao comentar que não temos suporte para FTP aberto?
- [ ] Explicamos porque não damos suporte?
- [ ] Encaminhamos as ferramentas necessárias?
